language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: sesion6-cabanes-travis-heroku
  on: master
  skip_cleanup: true
  api_key:
    secure: rJPAIfI7AWR1bt+VxPgxMrzfjPvffb5ef45HoRxPbFy5ekJJeWMz1Zyr6cX2u8qcC1MnRvSgAbjupfcjDp3smDTp0gJMnxEXLTbDedQtM8NOWJpVxF7W/qOpJhwNAPCp1heSOX3nzzxVU7q04lr9IO+A1GRnv+9Kerjn1yZ6GRn8mtP9cQ0qAz+peR+KcC23OAmbXSK8g0EkBD2/VXMbS/wIsiNt9GNK1i7J0jlGs9A1frAcCjq+AKZ9jAzh18q4l68W8m7awHLn8K2NfoZxOzkqdyw5nxOSF0avNimsL7WXR6ZeylO2tkOB25jYKlTZtqLqiq1aiwnjhmdsZc1eKUMz2wjxlXg5a1JapS7Rz4MXLNpV97TFmfXtl9foc+DOuh7e97NrHiJQGcoY9gbiNqyd//Lnee4MzopCFmFEI5ELKuvfwc8rkRJtoX/3eOtYzfJS2qIqpzvdTz1LzZdjF1QTZvueodJ7e+1wZhYKzbd/G22W765AvHaU+U4qZEudqe+E4t9VS9FBXe/ZIrlx5dRH6qQrB5uVQtaJf2FWTf7z3qXN6zsqRL/AgUF60Qzy0XMloagSw69/VVLOt/LdhNEkymyYUqzfp9wNRP+09t9FOhiGEAaQO6CRKWEGL6QOgmVFoD2mVexT84YFjFzmYRFk22GBZMewXqlpeQzXzBk=
